/var/spool/slurmd/job33438/slurm_script: line 10: cd: SSL_VAN: No such file or directory

----------------------------------------------------------------------------
  cuda:
----------------------------------------------------------------------------
     Versions:
        cuda/10.2
        cuda/11.0
        cuda/11.2
        cuda/11.3
        cuda/11.4
        cuda/11.5
        cuda/11.6
        cuda/12.0

----------------------------------------------------------------------------
  For detailed information about a specific "cuda" package (including how to load the modules) use the module's full name.
  Note that names that have a trailing (E) are extensions provided by other modules.
  For example:

     $ module spider cuda/12.0
----------------------------------------------------------------------------

 


CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/BTCV/main.py:119: UserWarning: 0 gpu 0
  warnings.warn(f"{args.rank} gpu {args.gpu}")
/home/karimimonsefi.1/SSL_VAN/BTCV/main.py:121: UserWarning: Batch size is: 2 epochs 5000
  warnings.warn(f"Batch size is: {args.batch_size} epochs {args.max_epochs}")
/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/transforms/post/array.py:176: UserWarning: `to_onehot=True/False` is deprecated, please use `to_onehot=num_classes` instead.
  warnings.warn("`to_onehot=True/False` is deprecated, please use `to_onehot=num_classes` instead.")
/home/karimimonsefi.1/SSL_VAN/BTCV/main.py:192: UserWarning: Total parameters count 23127538
  warnings.warn(f"Total parameters count {pytorch_total_params}")
/home/karimimonsefi.1/SSL_VAN/BTCV/main.py:196: UserWarning: Total args.checkpoint True
  warnings.warn(f"Total args.checkpoint {args.checkpoint}")
/home/karimimonsefi.1/SSL_VAN/BTCV/main.py:209: UserWarning: => loaded checkpoint 'True' (epoch 19) (bestacc 0.1449875831604004)
  warnings.warn("=> loaded checkpoint '{}' (epoch {}) (bestacc {})".format(
/home/karimimonsefi.1/SSL_VAN/BTCV/trainer.py:138: UserWarning: Writing Tensorboard logs to ./runs/BTCV/test_log
  warnings.warn(f"Writing Tensorboard logs to {args.logdir}")
/home/karimimonsefi.1/SSL_VAN/BTCV/trainer.py:147: UserWarning: 0  Fri Mar 24 08:10:06 2023  Epoch: 19
  warnings.warn(f"{args.rank}  {time.ctime()}  Epoch: {epoch}")
input_list/dataset_BTCV_List.json
/home/karimimonsefi.1/SSL_VAN/BTCV/trainer.py:53: UserWarning: Epoch 19/5000 0/12  loss: 3.5067  time 12.64s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/BTCV/trainer.py:53: UserWarning: Epoch 19/5000 1/12  loss: 3.5019  time 1.15s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/BTCV/trainer.py:53: UserWarning: Epoch 19/5000 2/12  loss: 3.5015  time 1.01s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/BTCV/trainer.py:53: UserWarning: Epoch 19/5000 3/12  loss: 3.5021  time 1.01s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/BTCV/trainer.py:53: UserWarning: Epoch 19/5000 4/12  loss: 3.5021  time 1.01s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/BTCV/trainer.py:53: UserWarning: Epoch 19/5000 5/12  loss: 3.5031  time 1.01s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/BTCV/trainer.py:53: UserWarning: Epoch 19/5000 6/12  loss: 3.5032  time 1.01s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/BTCV/trainer.py:53: UserWarning: Epoch 19/5000 7/12  loss: 3.5039  time 1.01s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/BTCV/trainer.py:53: UserWarning: Epoch 19/5000 8/12  loss: 3.5036  time 1.02s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/BTCV/trainer.py:53: UserWarning: Epoch 19/5000 9/12  loss: 3.5031  time 1.01s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/BTCV/trainer.py:53: UserWarning: Epoch 19/5000 10/12  loss: 3.5030  time 1.02s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/BTCV/trainer.py:53: UserWarning: Epoch 19/5000 11/12  loss: 3.5030  time 1.01s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/BTCV/trainer.py:153: UserWarning: Final training  19/4999  loss: 3.5030  time 23.96s
  warnings.warn("Final training  {}/{}  loss: {:.4f}  time {:.2f}s".format(epoch, args.max_epochs - 1,
Traceback (most recent call last):
  File "/home/karimimonsefi.1/SSL_VAN/BTCV/main.py", line 270, in <module>
    main()
  File "/home/karimimonsefi.1/SSL_VAN/BTCV/main.py", line 102, in main
    main_worker(gpu=0, args=args)
  File "/home/karimimonsefi.1/SSL_VAN/BTCV/main.py", line 249, in main_worker
    accuracy = run_training(
  File "/home/karimimonsefi.1/SSL_VAN/BTCV/trainer.py", line 163, in run_training
    val_avg_acc = val_epoch(
  File "/home/karimimonsefi.1/SSL_VAN/BTCV/trainer.py", line 68, in val_epoch
    for idx, batch_data in enumerate(loader):
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/transforms/transform.py", line 89, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/transforms/transform.py", line 53, in _apply_transform
    return transform(parameters)
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/transforms/croppad/dictionary.py", line 1171, in __call__
    self.randomize(label, fg_indices, bg_indices, image)
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/transforms/croppad/dictionary.py", line 1153, in randomize
    self.centers = generate_pos_neg_label_crop_centers(
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/transforms/utils.py", line 506, in generate_pos_neg_label_crop_centers
    for _ in range(num_samples):
TypeError: 'float' object cannot be interpreted as an integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/transforms/transform.py", line 89, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/transforms/transform.py", line 53, in _apply_transform
    return transform(parameters)
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/transforms/compose.py", line 173, in __call__
    input_ = apply_transform(_transform, input_, self.map_items, self.unpack_items, self.log_stats)
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/transforms/transform.py", line 113, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.croppad.dictionary.RandCropByPosNegLabeld object at 0x149ca47ec460>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/data/dataset.py", line 97, in __getitem__
    return self._transform(index)
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/data/dataset.py", line 83, in _transform
    return apply_transform(self.transform, data_i) if self.transform is not None else data_i
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/transforms/transform.py", line 113, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.compose.Compose object at 0x149ca47ec520>

